<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>regla de tormenta</name>
  <uuid>1a80f336-3a69-46a6-9390-27c1636f21ee</uuid>
  <locale>es_ES</locale>
  <definition><![CDATA[ si 
	Clima es alerta de tormenta
 entonces
   asignar a decisión "Quedece en casa! Hay alerta de tormenta." ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
